name: GitHub CI

on:
  push:
    # バージョン指定つきタグがプッシュされた時のみ実行
    tags:
      - 'v*'
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  deployments: write
  pages: write
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        # クロスプラットフォーム・ビルド
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      # Actions の基本設定
      - name: Check out Git repositry
        uses: actions/checkout@v3.5.2

      # Node.js のセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 16.x
          cache:
            npm

      # 依存パッケージのインストール
      - name: Install dependencies
        run: npm ci

      #### webpackなどによるビルドが必要なとき ####
      - name: Build
        run: npm run make

      # GitHub releases へデプロイ
      - name: Deploy
        env:
          # GITHUB_TOKEN は自動生成されるのでとくに設定は不要
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # NPM スクリプト名は 'release' にすることが必須
        run: npm run publish
        # run: npm run release
